# Generated by Django 5.1 on 2026-08-18 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courts.court'),
        ),
    ]
