# Generated by Django 5.1 on 2026-08-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('booking', 'Thông báo đặt sân'), ('review', 'Thông báo đánh giá'), ('play_request', 'Thông báo tìm bạn chơi'), ('system', 'Thông báo hệ thống')], max_length=50)),
                ('related_id', models.BigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
