# Generated by Django 5.1 on 2026-08-18 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complex_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complex_settings',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('weekday', 'Ngày thường'), ('weekend', 'Cuối tuần')], max_length=10)),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('price_per_slot', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'pricing_rules',
            },
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sport_types',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Trống'), ('locked', 'Đang giữ chỗ'), ('booked', 'Đã đặt')], max_length=10)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_slots',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('total_rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.complex_setting')),
            ],
            options={
                'db_table': 'courts',
            },
        ),
    ]
