# Generated by Django 5.1 on 2026-08-18 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricing',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.court'),
        ),
        migrations.AddField(
            model_name='court',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courts.sporttype'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.court'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
