# Generated by Django 5.2.17 on 2026-09-02 08:59

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complex_Setting',
            new_name='ComplexSetting',
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='start_date',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='locked_until',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='status',
        ),
        migrations.AlterField(
            model_name='court',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='courts.court'),
        ),
    ]
