# Generated by Django 5.2.17 on 2026-09-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_rename_complex_setting_complexsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='courts', to='courts.amenity'),
        ),
    ]
