# Generated by Django 5.1 on 2026-08-18 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayRequestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'play_request_participants',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_replies',
            },
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Mới chơi'), ('intermediate', 'Trung bình'), ('advanced', 'Khá'), ('pro', 'Chuyên nghiệp')], max_length=15)),
            ],
            options={
                'db_table': 'skill_levels',
            },
        ),
        migrations.CreateModel(
            name='PlayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_status', models.CharField(choices=[('beginner', 'Mới chơi'), ('intermediate', 'Trung bình'), ('advanced', 'Khá'), ('pro', 'Chuyên nghiệp')], max_length=15)),
                ('slot_number', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Đang tìm người'), ('full', 'Đã đủ người'), ('closed', 'Đã đóng')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
            options={
                'db_table': 'play_requests',
            },
        ),
    ]
