# Generated by Django 5.1 on 2026-08-18 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_initial'),
        ('community', '0001_initial'),
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playrequest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playrequestparticipant',
            name='play_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.playrequest'),
        ),
        migrations.AddField(
            model_name='playrequestparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.court'),
        ),
        migrations.AddField(
            model_name='review',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='replied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.review'),
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courts.sporttype'),
        ),
        migrations.AlterUniqueTogether(
            name='playrequestparticipant',
            unique_together={('play_request', 'player')},
        ),
    ]
