# Generated by Django 5.2.17 on 2026-09-02 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('community', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='playrequest',
            old_name='desired_status',
            new_name='desired_level',
        ),
        migrations.AddField(
            model_name='playrequestparticipant',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Đang tìm người'), ('full', 'Đã đủ người'), ('closed', 'Đã đóng')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='playrequestparticipant',
            name='play_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community.playrequest'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('booking', 'player')},
        ),
    ]
