# Generated by Django 5.2.17 on 2026-09-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar_url_user_avatar_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner_requested',
            field=models.BooleanField(default=False),
        ),
    ]
